### ISSUE TITLE
error to run code with debug

### ISSUE THREAD

**Issue by lethemagicbegin** [Santos-Enoque/flutter-web-dashboard-template#6]
hi, i have this error whene i run the program...what can i do?

`                                            ^^^^^
      color ??= Theme.of(context).textTheme.body1!.color;
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/charts_flutter-0.11.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45: Error: The getter 'body1' isn't defined for the class 'TextTheme'.

Failed to compile application.
`

**Comment by isoneday** [comment]
change dependecies charts_flutter  to

dependency_overrides:
 charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter

**Comment by imranissufo** [comment]
Applied this solution and it was solved, thanks

```
dependencies:
  //charts_flutter: ^0.10.0 -removed this line
  //added the following
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter

```
